'''
Arquivo para configurações de login e senha
Atenção para co
'''

USERNAME = ''  # USERNAME SALESFORCE
PASSWORD = ''  # PASSWORD SALESFORCE
SECURITY_TOKEN = ''  # SECURITY TOKEN DO SALESFORCE
SANDBOX = False

MUNDIPAGG_API = ''  # CHAVE API MUNDIPAGG

FILE_PATH = 'c:'